#! /usr/bin/env bash
# 2026 Tomasz Pakuła

CONFIG_PATH="/etc/p14s-wifi-reset.conf"
SEARCH_STRING="QCNFA765"

# give the computer time to settle
sleep 0.1s

# find wireless adapter
if [[ -f $CONFIG_PATH ]]; then
    SEARCH_STRING=$(cat $CONFIG_PATH | head -1)
    echo "Custom search string: $SEARCH_STRING"
fi

ID=$(lspci | grep "$SEARCH_STRING" | head -1 | cut -d " " -f 1)
if [[ -z $ID ]]; then
    echo "Adapter not found!"
    exit 1
fi

# remove adapter from pci bus
tee "/sys/bus/pci/devices/0000:$ID/remove" > /dev/null <<< 1
sleep 0.2s

# rescan to re-add adapter to the system
tee "/sys/bus/pci/rescan" > /dev/null <<< 1

echo "Sucessfully reset $SEARCH_STRING Wi-Fi adapter"

